### ISSUE TITLE
Heterogeneous graphs with multiple node types

### ISSUE THREAD

**Issue by nevliin** [benedekrozemberczki/FEATHER#2]
Hello, I am currently looking for a whole graph embedding method and discovered FEATHER. The implementation of FEATHER in the karateclub package does technically work on my graphs, but I am not sure it is correctly applied.

My graphs have multiple node types, and each node type has a different set of features. In your paper, you only explain the procedure for one type of node with one set of features. Does FEATHER adapt to the different node types? Do the characteristic functions only take nodes of the same type into account?

A quick answer would be immensely helpful for me, thank you in advance.

**Comment by benedekrozemberczki** [comment]
No it does not.
