### ISSUE TITLE
how to generate embeddings using your library if my input is in grapson(json) or graphml(xml) format?

### ISSUE THREAD

**Issue by anushka192001** [benedekrozemberczki/FEATHER#4]
how to generate embeddings using your library if my input is in grapson(json) or graphml(xml) format?

**Comment by sethGu** [comment]
Maybe transfer the format into FEATHER-like.
![image](https://user-images.githubusercontent.com/45868017/196894191-ca38b156-04da-479b-a2aa-ff5aba148179.png)

**Comment by anushka192001** [comment]
how to transfer to FEATHER-like?

**Comment by sethGu** [comment]
I guess for own dataset, traverse all the nodes into an Edge list, to record the adjacent info with the format of Adjacent List. 
Use a GNN or whatever encoder to do the node encoding with the format of Feature Maxtrix. 
Use ER_edges to do the ER_graphs as Adacent Matrix.
If own data is dataloader-like, iteration it.
